bert_model: 'distilbert-base-uncased'         # which bert model to use
content: ['title', 'category']                # which metadata attributes to use; options: ['title', 'category'], ['description'], ['title', 'category', 'description']
max_seq_length: 512                           # token truncation limit
pooling_strategy: 'cls'                       # methods for deriving the embeddings; options: 'cls', 'mean', 'max'
batch_size: 32
aggregation_method: 'avg'                     # strategy for creating the user profile vector; options: 'avg', 'weighted_avg', 'avg-pos'
pos_rating_threshold: 4.0                     # threshold for positive ratings
cold_start_strategy: 'zero'                   # backup mechanism for users with no interactions in the training set
similarity_metric: 'dot'                      # options: 'dot', 'cosine', 'euclidian'
score_mapping: False                          # True for Rating, False for Ranking
top_k: 10                                     # size of recommendation list
filter_interacted: False                      # whether to filter out items that have been interacted by the user
